---
- name: Ensure media group exists
  ansible.builtin.group:
    name: "{{ media_group }}"
    gid: "{{ media_gid }}"
    state: present

- name: Ensure media user exists
  ansible.builtin.user:
    name: "{{ media_user }}"
    uid: "{{ media_uid }}"
    group: "{{ media_group }}"
    comment: Media automation service account
    shell: /usr/sbin/nologin

- name: Install base packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Enable and start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Deploy sysctl hardening
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.d/99-media.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload sysctl
